In [1]:
import os
os.chdir('/content/drive/MyDrive/Colab Notebooks/地熱2')

In [3]:
import pandas as pd
df_excel = pd.ExcelFile('対象セグメント案_1.xlsx')

In [7]:
sheet_name = df_excel.sheet_names

In [11]:
df = df_excel.parse(sheet_name[0])

In [12]:
df.head()

  Well  #         Start time            End time               Interval
0  06T  1 2006-07-01 00:00:00 2006-09-21 16:00:00      2m 20d 16H 0M 0S
1  06T  2 2006-11-07 14:45:00 2007-12-20 09:55:00  1y 1m 12d 19H 10M 0S
2  06T  3 2007-12-26 15:35:00 2008-02-20 13:50:00     1m 24d 22H 15M 0S
3  06T  4 2008-02-29 15:05:00 2008-05-21 10:55:00     2m 21d 19H 50M 0S
4  06T  5 2008-08-12 16:35:00 2008-09-26 15:05:00     1m 13d 22H 30M 0S

In [13]:
df.to_csv('segment.csv')

In [16]:
df_2 = df.drop('#', axis=1)
print(df_2.head())

  Well         Start time            End time               Interval
0  06T 2006-07-01 00:00:00 2006-09-21 16:00:00      2m 20d 16H 0M 0S
1  06T 2006-11-07 14:45:00 2007-12-20 09:55:00  1y 1m 12d 19H 10M 0S
2  06T 2007-12-26 15:35:00 2008-02-20 13:50:00     1m 24d 22H 15M 0S
3  06T 2008-02-29 15:05:00 2008-05-21 10:55:00     2m 21d 19H 50M 0S
4  06T 2008-08-12 16:35:00 2008-09-26 15:05:00     1m 13d 22H 30M 0S

In [17]:
df.to_csv('segment_data.csv', index = False)